AWS_ACCESS_KEY: "your_aws_access_key_here"
AWS_SECRET_KEY: "your_aws_secret_key_here"

DATABASE_PASSWORD: "your_database_password_here"

IOT_API_KEY: "your_iot_api_key_here"
TRAFFIC_API_KEY: "your_traffic_api_key_here"
